### ISSUE TITLE
Requirements checklist

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#33]
Tracker for the features to be implemented - copied from https://github.com/domenic/infinite-list-study-group/edit/master/REQUIREMENTS.md.

Mark complete after providing implementation and documentation.

## P0
- [x] Accurate scrollbar position for elements that have been loaded
  - Implemented, see [demo/layout.html](https://github.com/valdrinkoshi/virtual-list/blob/master/demo/layout.html) (scroll, change items count, and observe scroll position is kept)
- [ ] Overall list structure supports screen readers and accessibility controls
- [x] Heterogeneous elements
  - Controlled by the user via [`newChild` property](https://github.com/valdrinkoshi/virtual-list/blob/master/README.md#newchild-property)
- [x] Fallback element UI
  - Controlled by the user via [`newChild` property](https://github.com/valdrinkoshi/virtual-list/blob/master/README.md#newchild-property)
  - see [demo/fallback.html](https://github.com/valdrinkoshi/virtual-list/blob/master/demo/fallback.html)
- [x] Grid layout
  - `<virtual-list layout="vertical-grid"></virtual-list>`
  - see [`layout` property](https://github.com/valdrinkoshi/virtual-list/blob/master/README.md#layout-property)
- [x] List headers/footers
  - Controlled by the user via [`newChild` property](https://github.com/valdrinkoshi/virtual-list/blob/master/README.md#newchild-property)
  - see [demo/header-footer.html](https://github.com/valdrinkoshi/virtual-list/blob/master/demo/header-footer.html)
- [x] Configurable layout and style for elements in the list
  - User can style content via `virtual-list > *` or by adding arbitrary classes to the stamped children
  - layout configurable via the [`layout` property](https://github.com/valdrinkoshi/virtual-list/blob/master/README.md#layout-property)
- [x] Clickable list elements
  - Controlled by the user via `newChild/updateChild` properties
  - example in the README.md
- [ ] indexability of not loaded content 

## P1
- [x] Find in page (ctl+F) highlights elements that have been loaded
- [x] Sub groups within the list (i.e. letter groupings for a contact list)
  - see [demo/header-footer.html](https://github.com/valdrinkoshi/virtual-list/blob/master/demo/header-footer.html)
- [ ] Maintain scroll position across page load
- [x] "Load more" button
  - see [demo/loadmore.html](https://github.com/valdrinkoshi/virtual-list/blob/master/demo/loadmore.html)
- [x] Ability to animate items in/out, changing sizes
  -  see [demo/dismissable/index.html](https://github.com/valdrinkoshi/virtual-list/blob/master/demo/dismissable/index.html)

## P2
- [x] Backed by remote data source
  - [demo/fallback.html](https://github.com/valdrinkoshi/virtual-list/blob/master/demo/fallback.html) shows how contacts are lazily loaded while we place a fallback during the loading
- [ ] Selectable list elements
  - TODO demo/selection.html
- [x] Rearrangeable list
- [ ] Find in page (ctl+F) highlights all elements in the list that haven't been loaded
- [ ] Accurate scrollbar position including elements that haven't been loaded
- [ ] Pull to refresh
  - TODO demo/pulltorefresh.html
- [ ] Discoverable by screen readers for elements in the list that haven't been loaded
- [ ] anchor refs pointing to dom not yet rendered
- [x] Horizontal scrolling
  - `<virtual-list layout="horizontal"></virtual-list>`
  - see `layout` property in the [README.md](https://github.com/valdrinkoshi/virtual-list/README.md)

**Comment by valdrinkoshi** [comment]
Re growable/expandable items, we enhanced demo/fallback.html in https://github.com/valdrinkoshi/virtual-scroller/pull/16 to show an example of expand/collapse.

Dismissable items should be very similar to do...PRs welcome :)

**Comment by sammymhowe** [comment]
Is there an option to NOT use your layout? Say we have our own fleshed out layout for a bunch of photos... and we just want to have the virtual scroller on those photos. How can we still keep our own layout?

**Comment by valdrinkoshi** [comment]
We need to define a layout, as virtual-scroller positions the stamped children via `position: absolute` + `transform: translate` for better performance. What would be your custom photo layout?

**Comment by sammymhowe** [comment]
We currently use flex box for our photo layout.

**Comment by valdrinkoshi** [comment]
I think `layout="vertical-grid"` should address exactly that. Currently the grid layout assumes all elements have the same size, but variable sizes is something we can support. Here an example http://jsbin.com/qahinef/1/edit?html,output

**Comment by kenchris** [comment]
What about a horizontal - vertical grid (`both-grid`?) - like a spreadsheet that scrolls in both directions

**Comment by sammymhowe** [comment]
I added in `layout="vertical-grid"` and I see the sizes changing in proportion to the window size changing, but each image still has the same height/width. We have images with the same height that grows/shrinks with the window, but the width varies line to line to make it display beautifully. So in your example, the width is the same across all photos, but in ours, the width changes photo to photo.

**Comment by kenchris** [comment]
What about fixed headers. Like the contact example, but where the header stays visible until replaced by another header. This is quite common in iOS apps

**Comment by kenchris** [comment]
> Dismissable items should be very similar to do...PRs welcome :)

Here you go!
https://github.com/valdrinkoshi/virtual-scroller/pull/96

**Comment by kenchris** [comment]
Maybe you can add the dismissable item to your checklist and cross it off? :) I would like you to add fixed headers as well

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
